# Generated by Django 4.0.2 on 2022-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fershampenuaz_SOSH_LP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FactNum', models.IntegerField()),
                ('OSZCode', models.CharField(max_length=11)),
                ('SNILS', models.CharField(max_length=11)),
                ('FamilyName', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('Patronymic', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('BirthDate', models.CharField(max_length=15)),
                ('BirthPlace', models.CharField(max_length=500)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Citizenship', models.CharField(max_length=3)),
                ('TypeDoc', models.IntegerField()),
                ('Series', models.CharField(max_length=4)),
                ('Number', models.CharField(max_length=6)),
                ('IssueDate', models.CharField(max_length=15)),
                ('Issuer', models.CharField(max_length=200)),
                ('SNILS2', models.CharField(max_length=11)),
                ('FamilyName2', models.CharField(max_length=100)),
                ('FirstName2', models.CharField(max_length=100)),
                ('Patronymic2', models.CharField(max_length=100)),
                ('Gender2', models.CharField(max_length=10)),
                ('BirthDate2', models.CharField(max_length=15)),
                ('BirthPlace2', models.CharField(max_length=500)),
                ('PhoneNumber2', models.CharField(max_length=10)),
                ('Citizenship2', models.CharField(max_length=3)),
                ('TypeDoc2', models.IntegerField()),
                ('Series2', models.CharField(max_length=4)),
                ('Number2', models.CharField(max_length=6)),
                ('IssueDate2', models.CharField(max_length=15)),
                ('Issuer2', models.CharField(max_length=200)),
                ('LMSZID', models.CharField(max_length=36)),
                ('categoryID', models.CharField(max_length=36)),
                ('decision_date', models.CharField(max_length=10)),
                ('dateStart', models.CharField(max_length=10)),
                ('dateFinish', models.CharField(max_length=10)),
                ('usingSign', models.IntegerField()),
                ('criteria', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=10)),
                ('measuryCode', models.CharField(max_length=2)),
                ('OKEICode', models.CharField(max_length=4)),
                ('contente', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('equivalentAmount', models.CharField(max_length=5)),
            ],
        ),
    ]
